tasks:
  - name: terraform
    env:
      TF_LOG: DEBUG
    before: |
      cd $PROJECT_ROOT
      source ./bin/install_terraform_cli
      
      source ./bin/set_tf_alias

  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd $PROJECT_ROOT
      source ./bin/install_aws_cli
      source ./bin/set_tf_alias
  - name: http-server
    before: |
      cd $PROJECT_ROOT
      npm install --global http-server
    command:
      http-server

  
  - name: sinatra
    before: | 
      cd $PROJECT_ROOT
      cd terratowns_mock_server
      bundle install
      bundle exec ruby server.rb    

vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform
